repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        description: Run flake8 within our project's environment.
        entry: poetry run flake8
        language: system
        types: [python]
        require_serial: true
      - id: pyright
        name: pyright
        description: Run flake8 within our project's environment.
        entry: poetry run pyright
        language: system
        types: [python]
        require_serial: true
